# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/acc_best"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 20

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1234
      n_startup_trials: 20  # number of random sampling runs before optimization starts

    # define hyperparameter search space
    params:
      model.optimizer.lr: interval(0.005, 0.01)
      model.net.use_raw : True
      model.net.use_bandpass : False
      model.net.use_bandpass_fft : False
      model.net.use_stat : True
      model.net.use_fft_stat : True
      model.net.use_eofft: True
      model.net.use_envelope: True
      model.net.use_envelope_spectrum: False
      model.net.out_channel1_size: 16
      model.net.out_channel2_size: 32
      model.net.out_channel3_size: 64
      model.net.out_channel4_size: 8
      model.net.out_channel5_size: 4
      model.net.out_channel6_size: 2
      model.net.kernel1_size: 64
      model.net.kernel2_size: 32
      model.net.kernel3_size: 16
      model.net.kernel4_size: 8
      model.net.kernel5_size: 4
      model.net.kernel6_size: 2
      model.net.lstm_hidden_size: 64
      model.net.dense1_out_size : 64
      model.net.dense2_out_size : 16
      model.net.output_size : 5
      model.net.topk_freq : 10
      model.net.discriminator_dense1_outsize : 64
      model.net.discriminator_dense2_outsize : 16