_target_: src.models.protomaml_module.ProtoMAMLModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 20

net:
  _target_: src.models.components.conv_lstm_classifier_no_dropout.CONV_LSTM_Classifier
  use_raw_bandpass_filterd : True
  use_fft_bandpass_filterd : True
  out_channel1_size : 16
  out_channel2_size : 64
  out_channel3_size : 32
  out_channel4_size : 8
  kernel1_size : 64
  kernel2_size : 32
  kernel3_size : 16
  kernel4_size : 4
  lstm_hidden_size : 128
  output_size: 5